# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
URVERSION = $(shell urweb -version)
.PHONY: all
all: ./Compet.exe ./Compet.sql ./Makefile
.PHONY: dropdb
dropdb: ./Compet.db ./Makefile
./Compet.db: ./Compet.exe ./Compet.sql ./Makefile
	dropdb --if-exists Compet
	createdb Compet
	psql -f ./Compet.sql Compet
	touch ./Compet.db
./Compet.exe: .fix-multy1
./Compet.urp: ./Makefile ./lib/uru3/Bootstrap/lib.urp ./src/Compet.ur ./src/Compet.urs ./src/Crud.ur ./src/Crud.urs ./src/Templ.ur ./src/Templ.urs .cake3/tmpCompet.in0 autogen/Compet_css.ur autogen/Compet_css.urs autogen/Compet_css_c.h autogen/Compet_css_c.o
	cat .cake3/tmpCompet.in0 > ./Compet.urp
.cake3/tmpCompet.in0: ./Makefile
	-rm -rf .cake3/tmpCompet.in0
	echo 'allow mime text/javascript' >> .cake3/tmpCompet.in0
	echo 'allow mime text/css' >> .cake3/tmpCompet.in0
	echo 'allow mime image/jpeg' >> .cake3/tmpCompet.in0
	echo 'allow mime image/png' >> .cake3/tmpCompet.in0
	echo 'allow mime image/gif' >> .cake3/tmpCompet.in0
	echo 'allow mime application/octet-stream' >> .cake3/tmpCompet.in0
	echo 'allow url /Compet/main' >> .cake3/tmpCompet.in0
	echo 'allow url /Compet/users' >> .cake3/tmpCompet.in0
	echo 'allow url /Compet/about' >> .cake3/tmpCompet.in0
	echo 'database dbname=Compet' >> .cake3/tmpCompet.in0
	echo 'safeGet Compet/main' >> .cake3/tmpCompet.in0
	echo 'sql ./Compet.sql' >> .cake3/tmpCompet.in0
	echo 'library ./lib/uru3/Bootstrap' >> .cake3/tmpCompet.in0
	echo 'include autogen/Compet_css_c.h' >> .cake3/tmpCompet.in0
	echo 'link autogen/Compet_css_c.o' >> .cake3/tmpCompet.in0
	echo 'ffi autogen/Compet_css_c' >> .cake3/tmpCompet.in0
	echo 'ffi autogen/Compet_css_js' >> .cake3/tmpCompet.in0
	echo 'allow mime text/css' >> .cake3/tmpCompet.in0
	echo 'safeGet Compet_css/blobpage' >> .cake3/tmpCompet.in0
	echo 'safeGet Compet_css/blob' >> .cake3/tmpCompet.in0
	echo '' >> .cake3/tmpCompet.in0
	echo '$$/list' >> .cake3/tmpCompet.in0
	echo '$$/string' >> .cake3/tmpCompet.in0
	echo 'autogen/Compet_css' >> .cake3/tmpCompet.in0
	echo './src/Templ' >> .cake3/tmpCompet.in0
	echo './src/Crud' >> .cake3/tmpCompet.in0
	echo './src/Compet' >> .cake3/tmpCompet.in0
./Compet.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: ./Compet.urp ./Makefile $(call GUARD,URVERSION)
	urweb -dbms postgres ./Compet
autogen/Compet_css_c.o: ./Makefile autogen/Compet_css_c.c $(call GUARD,URCC) $(call GUARD,URINCL) $(call GUARD,UR_CFLAGS)
	$(URCC) -c $(URINCL) $(UR_CFLAGS)  -o autogen/Compet_css_c.o autogen/Compet_css_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@
$(call GUARD,UR_CFLAGS):
	rm -f .cake3/GUARD_UR_CFLAGS_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: dropdb
dropdb: .fix-multy1
.PHONY: ./Compet.db
./Compet.db: .fix-multy1
.PHONY: ./Compet.exe
./Compet.exe: .fix-multy1
.PHONY: ./Compet.urp
./Compet.urp: .fix-multy1
.PHONY: .cake3/tmpCompet.in0
.cake3/tmpCompet.in0: .fix-multy1
.PHONY: ./Compet.sql
./Compet.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -C ./lib/uru3/Bootstrap -f Makefile 
	MAIN=1 $(MAKE) -f ./Makefile $(MAKECMDGOALS)
.PHONY: autogen/Compet_css_c.o
autogen/Compet_css_c.o: .fix-multy1

endif
.PHONY: clean
clean: 
	-rm ./Compet.db ./Compet.exe ./Compet.sql ./Compet.urp .cake3/tmpCompet.in0 autogen/Compet_css_c.o
	-rm -rf .cake3

endif
